bibstat/urls.py
from django.urls import re_path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from django_js_reverse.views import urls_js

import libstat
from libstat.apis.open_data import data_api, observation_api, export_api
from libstat.apis.terms import term_api, terms_api

from libstat.views.auth import login
from libstat.views.administration import administration, create_new_collection
from libstat.views.articles import article, articles, articles_delete
from libstat.views.dispatches import dispatches, dispatches_delete, dispatches_send
from libstat.views.index import index
from libstat.views.reports import reports, report
from libstat.views.surveys import (
    surveys,
    surveys_statuses,
    surveys_export,
    surveys_export_with_previous,
    surveys_activate,
    surveys_inactivate,
    surveys_overview,
    import_and_create,
    remove_empty,
    match_libraries,
    surveys_update_library,
)
from libstat.views.survey import (
    survey,
    survey_status,
    survey_notes,
    example_survey,
    sigel_survey,
    release_survey_lock,
)
from libstat.views.variables import (
    variables,
    edit_variable,
    create_variable,
    replaceable_variables,
)

urlpatterns = [
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
    re_path(
        r"^humans\.txt$",
        TemplateView.as_view(
            template_name="humans.txt", content_type="text/plain; charset=utf-8"
        ),
        name="humans",
    ),
    # APIs
    re_path(r"^data$", data_api, name="data_api"),
    re_path(r"^data/(?P<observation_id>\w+)$", observation_api, name="observation_api"),
    re_path(r"^def/terms$", terms_api, name="terms_api"),
    re_path(r"^def/terms/(?P<term_key>\w+)$", term_api, name="term_api"),
    re_path(r"^export$", export_api, name="export_api"),
    # Auth
    re_path(r"^login$", login, name="login"),
    re_path(r"^logout$", LogoutView.as_view(),  name='logout'),
    # Index
    re_path(r"^$", index, name="index"),
    re_path(r"^admin$", libstat.views.index.admin, name="admin"),
    # Articles
    re_path(r"^article/(?P<article_id>\w+)$", article, name="article"),
    re_path(r"^article$", article, name="article"),
    re_path(r"^articles$", articles, name="articles"),
    re_path(
        r"^articles/delete/(?P<article_id>\w+)$",
        articles_delete,
        name="articles_delete",
    ),
    # Reports
    re_path(r"^reports$", reports, name="reports"),
    re_path(r"^report$", report, name="report"),
    # Administration
    re_path(
        r"^administration/create_new_collection$",
        create_new_collection,
        name="create_new_collection",
    ),
    re_path(r"^administration$", administration, name="administration"),
    # Survey
    re_path(r"^surveys$", surveys, name="surveys"),
    re_path(r"^surveys/example$", example_survey, name="example_survey"),
    re_path(r"^surveys/activate$", surveys_activate, name="surveys_activate"),
    re_path(r"^surveys/inactivate$", surveys_inactivate, name="surveys_inactivate"),
    re_path(r"^surveys/export$", surveys_export, name="surveys_export"),
    re_path(
        r"^surveys/export_with_previous$",
        surveys_export_with_previous,
        name="surveys_export_with_previous",
    ),
    re_path(
        r"^surveys/import_and_create$",
        import_and_create,
        name="surveys_import_and_create",
    ),
    re_path(r"^surveys/remove_empty$", remove_empty, name="surveys_remove_empty"),
    re_path(
        r"^surveys/match_libraries$", match_libraries, name="surveys_match_libraries"
    ),
    re_path(r"^surveys/status$", surveys_statuses, name="surveys_statuses"),
    re_path(
        r"^surveys/overview/(?P<sample_year>\w+)$",
        surveys_overview,
        name="surveys_overview",
    ),
    re_path(
        r"^surveys/status/(?P<survey_id>\w+)$", survey_status, name="survey_status"
    ),
    re_path(r"^surveys/notes/(?P<survey_id>\w+)$", survey_notes, name="survey_notes"),
    re_path(
        r"^surveys/update_library$",
        surveys_update_library,
        name="surveys_update_library",
    ),
    re_path(r"^surveys/sigel/(?P<sigel>\w+)$", sigel_survey, name="sigel_survey"),
    re_path(
        r"^surveys/unlock/(?P<survey_id>\w+)$",
        release_survey_lock,
        name="release_survey_lock",
    ),
    re_path(r"^surveys/(?P<survey_id>\w+)$", survey, name="survey"),
    # Dispatch
    re_path(r"^dispatches$", dispatches, name="dispatches"),
    re_path(r"^dispatches/delete$", dispatches_delete, name="dispatches_delete"),
    re_path(r"^dispatches/send", dispatches_send, name="dispatches_send"),
    # Variables
    re_path(r"^variables$", variables, name="variables"),
    re_path(r"^variables/new$", create_variable, name="create_variable"),
    re_path(
        r"^variables/replaceable$", replaceable_variables, name="replaceable_variables"
    ),
    re_path(r"^variables/(?P<variable_id>\w+)$", edit_variable, name="edit_variable"),
    # Other
    # re_path(r'^.well-known/void$', RedirectView.as_view(url=reverse('open_data'), permanent=False)),
    re_path(r"^jsreverse/$", urls_js, name="js_reverse"),
]

libstat/forms/article.py
from django import forms

from libstat.models import Article


class ArticleForm(forms.Form):
    title = forms.CharField(
        label="Rubrik",
        widget=forms.TextInput(attrs={"class": "form-control form-article-input"}),
    )
    content = forms.CharField(
        label="Innehåll",
        widget=forms.Textarea(attrs={"class": "form-control form-article-input"}),
    )

    def __init__(self, *args, **kwargs):
        self.article = kwargs.pop("article", None)
        super(ArticleForm, self).__init__(*args, **kwargs)
        if self.article:
            self.fields["title"].initial = self.article.title
            self.fields["content"].initial = self.article.content

    def save(self):
        article = self.article if self.article else Article()
        article.title = self.cleaned_data["title"]
        article.content = self.cleaned_data["content"]
        article.save()

libstat/forms/variable.py
from django import forms
from libstat.models import Variable
from libstat.utils import VARIABLE_TYPES, SURVEY_TARGET_GROUPS

__author__ = "vlovgr"


class VariableForm(forms.Form):
    active_from = forms.DateField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )
    active_to = forms.DateField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )

    question = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )
    question_part = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )
    category = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )
    sub_category = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )

    type = forms.ChoiceField(required=True, widget=forms.RadioSelect())

    # Since this is a checkbox, a value will only be returned in form if the
    # checkbox is checked. Hence the required=False.
    is_public = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={"value": "1"})
    )

    target_groups = forms.MultipleChoiceField(
        required=True, widget=forms.CheckboxSelectMultiple()
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": "2"})
    )
    comment = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={"class": "form-control", "rows": "2"}),
    )

    replaces = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"class": "form-control"})
    )

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop("instance", None)
        super(VariableForm, self).__init__(*args, **kwargs)
        if not self.instance:
            self.fields["key"] = forms.CharField(
                required=True, widget=forms.TextInput(attrs={"class": "form-control"})
            )

        self.fields["type"].choices = [type for type in VARIABLE_TYPES]
        self.fields["target_groups"].choices = [
            target_group for target_group in SURVEY_TARGET_GROUPS
        ]

        if self.instance:
            self.fields["active_from"].initial = (
                self.instance.active_from.date() if self.instance.active_from else None
            )
            self.fields["active_to"].initial = (
                self.instance.active_to.date() if self.instance.active_to else None
            )
            self.fields["question"].initial = self.instance.question
            self.fields["question_part"].initial = self.instance.question_part
            self.fields["category"].initial = self.instance.category
            self.fields["sub_category"].initial = self.instance.sub_category
            self.fields["type"].initial = self.instance.type
            self.fields["is_public"].initial = self.instance.is_public
            self.fields["target_groups"].initial = self.instance.target_groups
            self.fields["description"].initial = self.instance.description
            self.fields["comment"].initial = self.instance.comment
            self.fields["replaces"].initial = (
                ", ".join([str(v.id) for v in self.instance.replaces])
                if self.instance.replaces
                else ""
            )
            self.replaces_initial_value = ", ".join(
                ["{}:{}".format(v.key, str(v.id)) for v in self.instance.replaces]
                if self.instance.replaces
                else []
            )

    def clean(self):
        cleaned_data = super(VariableForm, self).clean()

        replaces = cleaned_data["replaces"] if "replaces" in cleaned_data else None
        active_from = (
            cleaned_data["active_from"] if "active_from" in cleaned_data else None
        )
        if replaces and not active_from:
            self._errors["replaces"] = self.error_class(
                ["Ange när ersättning börjar gälla genom att sätta 'Giltig fr o m'"]
            )
            self._errors["active_from"] = self.error_class(["Måste anges"])

            del cleaned_data["replaces"]
            del cleaned_data["active_from"]

        active_to = cleaned_data["active_to"] if "active_to" in cleaned_data else None
        if (
            self.instance
            and self.instance.replaced_by
            and active_to
            and self.instance.active_to
            and active_to != self.instance.active_to.date()
        ):
            self._errors["active_to"] = self.error_class(["Styrs av ersättande term"])
            del cleaned_data["active_to"]
        return cleaned_data

    def save(self, commit=True, user=None, activate=False):
        variable = self.instance if self.instance else Variable(is_draft=True)
        variable.key = self.instance.key if self.instance else self.cleaned_data["key"]
        variable.active_from = self.cleaned_data[
            "active_from"
        ]  # Need to convert to UTC? It's a date and not a datetime...
        variable.active_to = (
            self.instance.active_to
            if self.instance and self.instance.replaced_by
            else self.cleaned_data["active_to"]
        )
        variable.question = self.cleaned_data["question"]
        variable.question_part = self.cleaned_data["question_part"]
        variable.category = self.cleaned_data["category"]
        variable.sub_category = self.cleaned_data["sub_category"]
        variable.type = self.cleaned_data["type"]
        variable.is_public = self.cleaned_data["is_public"]
        variable.target_groups = self.cleaned_data["target_groups"]
        variable.description = self.cleaned_data["description"]
        variable.comment = self.cleaned_data["comment"]
        if activate:
            variable.is_draft = False

        to_replace = (
            self.cleaned_data["replaces"].split(", ")
            if self.cleaned_data["replaces"]
            else []
        )
        modified_siblings = variable.replace_siblings(
            to_replace, switchover_date=variable.active_from
        )

        if commit:
            variable.save_updated_self_and_modified_replaced(modified_siblings)

        return variable

libstat/views/administration.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required

from libstat.models import Survey
from libstat.views.surveys import _create_new_collection

import datetime

current_year = datetime.datetime.now().year


@permission_required("is_superuser", login_url="index")
def administration(request):
    context = {
        "possible_year_choices": [
            current_year - 1,
            current_year,
            current_year + 1,
            current_year + 2,
            current_year + 3,
            current_year + 4,
        ],
        "message": request.session.pop("message", None),
    }

    return render(request, "libstat/administration.html", context)


@permission_required("is_superuser", login_url="index")
def create_new_collection(request):
    sample_year = request.POST.get("year")

    if int(sample_year) in [
        int(year) for year in Survey.objects.distinct("sample_year")
    ]:
        request.session[
            "message"
        ] = "Kan inte skapa en ny omgång för {}, den omgången finns redan.".format(
            sample_year
        )
        return redirect(reverse("administration"))
    elif sample_year:
        _create_new_collection(int(sample_year))
        return redirect(reverse("surveys"))

libstat/views/articles.py
from django.contrib.auth.decorators import permission_required
from django.urls import reverse
from django.shortcuts import render, redirect

from libstat.forms.article import ArticleForm
from libstat.models import Article


@permission_required("is_superuser", login_url="index")
def articles(request):
    context = {
        "articles": Article.objects.order_by("-date_published"),
        "nav_articles_css": "active",
    }
    return render(request, "libstat/articles.html", context)


@permission_required("is_superuser", login_url="index")
def article(request, article_id=None):
    article = Article.objects.get(pk=article_id) if article_id else None

    if request.method == "POST":
        form = ArticleForm(request.POST, article=article)
        if form.is_valid():
            form.save()
        return redirect(reverse("articles"))

    if request.method == "GET":
        context = {"form": ArticleForm(article=article)}
        return render(request, "libstat/article.html", context)


@permission_required("is_superuser", login_url="index")
def articles_delete(request, article_id=None):
    if request.method == "POST":
        article = Article.objects.get(pk=article_id) if article_id else None
        if article:
            article.delete()
        return redirect(reverse("articles"))

libstat/views/index.py
import logging

from django.urls import reverse
from django.shortcuts import render, redirect

from bibstat import settings
from libstat.models import Article, OpenData


logger = logging.getLogger(__name__)


def index(request):
    context = {
        "articles": Article.objects.all().order_by("-date_published"),
        "open_data_years": sorted(
            OpenData.objects.distinct("sample_year"), reverse=True
        ),
        "blog_url": settings.BIBSTAT_BLOG_BASE_URL,
        "api_base_url": settings.API_BASE_URL,
        "environment": settings.ENVIRONMENT,
    }

    return render(request, "libstat/index.html", context)


def admin(request):
    if request.user.is_authenticated:
        return redirect(reverse("surveys"))

    return render(request, "libstat/admin.html")

libstat/templates/libstat/variable/edit.html
{% load i18n %}
{% load libstat_tags %}

<form class="edit-variable-form" method="post" action="{{ form_url }}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">{% trans 'Stäng' %}</span></button>
                <h4 class="modal-title">{{ modal_title }}</h4>
            </div>
            <div class="modal-body">
                {% csrf_token %}

                <span class="general-errors text-danger form-validation"></span>

                {% if  mode == 'edit' and not form.instance.state.state == "current" %}
                    <div class="panel panel-default">
                        <div class="panel-body warnings">
                            {% if form.instance.replaced_by %}
                                <span class="text-warning">
                <span class=" glyphicon glyphicon-warning-sign"></span>
                <span>
                  {% trans "Ersätts av" %} 
                  <a id="replaced_by" href="#"
                     data-form="{% url 'edit_variable' form.instance.replaced_by.id %}">{{ form.instance.replaced_by.key }}</a>
                  {% trans "från och med" %} {{ form.instance.active_to|utc_tz|date:"Y-m-d" }}
                </span>
              </span>
                            {% endif %}
                            {% if form.instance.is_draft %}
                                <span class="text-info">
                <span class=" glyphicon glyphicon-info-sign"></span>
                <span>{% trans "Detta är ett utkast som ej är synligt för användare eller som öppna data. För att aktivera utkastet, klicka på knappen 'Aktivera' nedan." %}</span>
              </span>
                            {% endif %}
                            {% if form.instance.state.state == "pending" %}
                                <span class="text-info">
                <span class=" glyphicon glyphicon-info-sign"></span>
                <span>{% trans "Den här termen börjar gälla" %} {{ form.instance.active_from|utc_tz|date:"Y-m-d" }}</span>
              </span>
                            {% endif %}
                            {% if form.instance.state.state == "discontinued" %}
                                <span class="text-info">
                <span class=" glyphicon glyphicon-info-sign"></span>
                <span>{% trans "Den här termen slutade vara giltig" %} {{ form.instance.active_to|utc_tz|date:"Y-m-d" }}</span>
              </span>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                {% if mode == 'create' %}
                    <div class="form-group key" data-field="key">
                        <label for="id_key">{% trans "Nyckel (unik)" %}</label>
                        <span class="text-danger form-validation after"></span>
                        {{ form.key }}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    </div>
                {% endif %}


                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group active_from" data-field="active_from">
                            <label for="id_active_from">{% trans "Giltig fr o m" %}</label>
                            <span class="text-danger form-validation after"></span>

                            <div class="input-group date">
                                {{ form.active_from }}<span class="input-group-addon"><i
                                        class="glyphicon glyphicon-th"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group active_to" data-field="active_to">
                            <label for="id_active_to">{% trans "Giltig till" %}</label>
                            <span class="text-danger form-validation after"></span>

                            <div class="input-group date">
                                <input id="id_active_to" class="form-control" type="text" name="active_to"
                                       value="{{ form.active_to.value|utc_tz|date:"Y-m-d" }}"
                                       {% if form.instance.replaced_by %}disabled="disabled"{% endif %}/>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group replaces" data-field="replaces">
                    <label for="id_replaces">{% trans "Ersätter termer" %}</label>
                    <input type="hidden" id="id_replaces_initial" value="{{ form.replaces_initial_value }}"/>
                    <span class="text-danger form-validation after"></span>
                    {{ form.replaces }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
                <div class="form-group question" data-field="question">
                    <label for="id_question">{% trans "Formulärfråga (gruppfråga i enkät)" %}</label>
                    <span class="text-danger form-validation after"></span>
                    {{ form.question }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
                <div class="form-group question_part" data-field="question_part">
                    <label for="id_question_part">{% trans "Delfråga (rad i rapport)" %}</label>
                    <span class="text-danger form-validation after"></span>
                    {{ form.question_part }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
                <div class="form-group category" data-field="category">
                    <label for="id_category">{% trans "Huvudgrupp" %}</label>
                    <span class="text-danger form-validation after"></span>
                    {{ form.category }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
                <div class="form-group sub_category" data-field="sub_category">
                    <label for="id_sub_category">{% trans "Undergrupp (rad i enkät)" %}</label>
                    <span class="text-danger form-validation after"></span>
                    {{ form.sub_category }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
                <div class="form-group type" data-field="type">
                    <label>{% trans "Enhet" %}</label>
                    <span class="text-danger form-validation after"></span>

                    <div>
                        {% for type_choice in form.type %}
                            <label class="radio-inline">
                                {{ type_choice.tag }}
                                {{ type_choice.choice_label }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group is_public" data-field="is_public">
                    <label>{% trans "Synlighet" %}</label>
                    <span class="text-danger form-validation after"></span>

                    <div class="checkbox">
                        {{ form.is_public }}
                        {% trans "Termen visas som öppna data" %}
                    </div>
                </div>
                <div class="form-group target_groups" data-field="target_groups">
                    <label>{% trans "Bibliotekstyper" %}</label>
                    <span class="text-danger form-validation after"></span>

                    <div>
                        {% for target_group in form.target_groups %}
                            <label class="checkbox-inline">
                                {{ target_group.tag }}
                                {{ target_group.choice_label }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group description" data-field="description">
                    <label for="description">{% trans "Beskrivning" %}</label>
                    <span class="text-danger form-validation after"></span>
                    {{ form.description }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
                <div class="form-group comment" data-field="comment">
                    <label for="comment">{% trans "Kommentar (visas ej publikt)" %}</label>
                    <span class="text-danger form-validation after"></span>
                    {{ form.comment }}
                    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                </div>
            </div>

            <div class="modal-footer">
                <input type="hidden" id="submit_action" name="submit_action" value="save"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Avbryt" %}</button>
                {% if mode == 'create' %}
                    <input type="submit" class="btn btn-primary" value="{% trans 'Spara utkast' %}"/>
                {% elif form.instance.is_draft %}
                    <input type="submit" class="btn btn-primary" value="{% trans 'Spara utkast' %}"/>
                    <input type="submit" id="save_and_activate" class="btn btn-primary" value="{% trans 'Spara och aktivera' %}"/>
                    <input type="submit" id="delete" class="btn btn-danger" value="{% trans 'Ta bort' %}"/>
                {% else %}
                    <input type="submit" class="btn btn-primary" value="{% trans 'Spara ändringar' %}"/>
                    {% if form.instance.is_deletable %}
                        <input type="submit" id="delete" class="btn btn-danger" value="{% trans 'Ta bort' %}"/>
                    {% endif %}
                {% endif %}
            </div>

        </div>
    </div>
</form>